apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
    - name: web
      port: 8080
      targetPort: web
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:22.0.1
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
#            - name: KC_HTTP_RELATIVE_PATH
#              value: "keycloak"
#            - name: KC_HOSTNAME_PATH
#              value: "keycloak"
#          ports:
#            - name: web
#              containerPort: 8080
#          readinessProbe:
#            httpGet:
#              path: /keycloak/health/ready
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 1
#            failureThreshold: 20
#          startupProbe:
#            httpGet:
#              path: /keycloak/health/ready
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 1
#            failureThreshold: 20
#          livenessProbe:
#            httpGet:
#              path: /keycloak/health/ready
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 1
#            failureThreshold: 20
#          readinessProbe:
#            httpGet:
#              path: /health/ready
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 1
#            failureThreshold: 2
#          startupProbe:
#            httpGet:
#              path: /health/ready
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 1
#            failureThreshold: 2
#          livenessProbe:
#            httpGet:
#              path: /health/ready
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 1
#            failureThreshold: 2
