# echo -n 'password' | base64
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: keycloak-cnpg-super-user-secret
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-pg
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  superuserSecret:
    name: keycloak-cnpg-super-user-secret
  storage:
    size: 1Gi
